#!/usr/bin/env perl

my $input = 't=';
while (<STDIN>) {
      $input .= qq($_);
}
$input =~ s/\\/\\\\/g;
$input =~ s/"/\\"/g;
$input =~ s/`/\\`/g;
$input .= '"';
$data = '"' . $input;
print $input;
print `curl -id $data http://p.xqz.ca/ 2>/dev/null | grep ^Location | sed -e 's/Location: //'`
